import { bootstrapApplication } from "@angular/platform-browser";
import { AppComponent } from "./app/app.component";
import { appConfig } from "./app/app.config";
import { registerLocaleData } from "@angular/common";
import localeFr from "@angular/common/locales/fr";
import localeEs from "@angular/common/locales/es";
import localePt from "@angular/common/locales/pt";
import localeDe from "@angular/common/locales/de";
import localeIt from "@angular/common/locales/it";
import localeKo from "@angular/common/locales/ko";
import localeRu from "@angular/common/locales/ru";
import localeJa from "@angular/common/locales/ja";
import localeNl from "@angular/common/locales/nl";
import localeAr from "@angular/common/locales/ar";
import localeHi from "@angular/common/locales/hi";
import localePl from "@angular/common/locales/pl";
import localeSv from "@angular/common/locales/sv";
import localeTr from "@angular/common/locales/tr";
import localeVi from "@angular/common/locales/vi";
import localeTh from "@angular/common/locales/th";

registerLocaleData(localeFr);
registerLocaleData(localeEs);
registerLocaleData(localePt);
registerLocaleData(localeDe);
registerLocaleData(localeIt);
registerLocaleData(localeKo);
registerLocaleData(localeRu);
registerLocaleData(localeJa);
registerLocaleData(localeNl);
registerLocaleData(localeAr);
registerLocaleData(localeHi);
registerLocaleData(localePl);
registerLocaleData(localeSv);
registerLocaleData(localeTr);
registerLocaleData(localeVi);
registerLocaleData(localeTh);

bootstrapApplication(AppComponent, appConfig).catch((err) => console.error(err));
